#!/bin/bash

#make changes in the files
#change in the file sim.sh

folder=feb18
orgfile="orgsim.sh"
plotsimpy="orgplotSim.py"
orgcorr="orgcorrection.py"
sed "s/simdir/${folder}/" "${orgfile}" > sim.sh

#run the file sim.sh
echo "Running sim.sh file..."
bash sim.sh

sleep 3
#modify orgplotSim.py
echo "Editing file:\t${plotsimpy}"
sed "s/simdir/${folder}/" "${plotsimpy}" > plotSim.py 

sleep 3
#running the file plotSim.py
echo "running the file plotSim.sh"
bash plotSim.sh

#edit the file orgcorrection.py
echo "Editing file:\t${orgcorr}"
sed "s/simdir/${folder}/" "${orgcorr}" > correction.py 
echo "running the file correction.sh"
bash correction.sh
